### ISSUE TITLE
[Suggestion] Python3 requirements note

### ISSUE THREAD

**Issue by wogong** [wzyboy/awesome-beancount#8]
For users' convenience, it would be better to note that the importers(at least the `cmb_credit_cards.py` and `cmb_debit_cards.py`) require python3.

**Comment by wzyboy** [comment]
I leave the shebang as is deliberately, per [this blog](http://carreau.github.io/posts/planning-an-early-death-for-python-2.html). As Beancount does not support Legacy Python after all, it is reasonable for Beancount-related tools to drop support for Legacy Python.
