### ISSUE TITLE
Let's move to cn-beancount

### ISSUE THREAD

**Issue by erickguan** [wzyboy/awesome-beancount#9]
I think we can create a new repo `cn-beancount` where we can document in Chinese. Then we can change this repo to a `awesome-*` repo following the guidelines.

Would you like this move?
@sycx @wzyboy @wogong

**Comment by wzyboy** [comment]
This repository tends to be a collection of various Beancount-related tools, not necessary those for financial institutes in China. Renaming the repository is fine, but maybe to another name.

**Comment by erickguan** [comment]
Sure thing, I can try more names:

beancount-tools: intuitive, hard to be distinguished from official toolsets.
beanconut-swiss: abbr. Swiss Army Knife
swiss-beancount: much helpful to be distinguished
beancount-toolbox: simple and clear
toolbox-beancont: looks hairy
beancount-kit: a bit confusing...

I think we need opinions from everyone.
